name: Frontend React

on:
    push:
        branches: ['main']

jobs:
    build:
        runs-on: self-hosted

        env:
            VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}

        steps:
            - uses: actions/checkout@v3

            - run: yarn install
            - run: yarn build
            - run: rm -rf /var/www/frontend/*
            - run: cp -r build/* /var/www/frontend
